### ISSUE TITLE
Error when trying to read XML file

### ISSUE THREAD

**Issue by ignatirabo** [LukeSerne/DecompVis#4]
I am trying to read an XML file with DecompVisor, but I get the following output.
```
A fatal error occurred while communicating with the decomp_dbg executable. Loading this xml file has been cancelled. A stack trace of the exception is shown below:

Traceback (most recent call last):
  File "/home/eclypsium/git/DecompVis/main.py", line 153, in _handle_set_xml_file
    self._parse_xml_file(pathlib.Path(file_name))
  File "/home/eclypsium/git/DecompVis/main.py", line 180, in _parse_xml_file
    raise ValueError(f"Did not find 'bytechunk' elements in the provided XML!")
ValueError: Did not find 'bytechunk' elements in the provided XML!
```

I am using Ghidra 11.2.1, and I exported the program from the Ghidra UI. Ghidra generated two files: `hello_world.xml` and `hello_world.bytes`.

I generated an ELF binary from the following code.
```
#include <stdio.h>
int main() {
   printf("Hello, World!");
   return 0;
}
```

Any help is appreciated. Thank you!

**Comment by LukeSerne** [comment]
Thanks for submitting an issue! Using the 11.2.1 release from Github, when I click "debug function decompilation" when the `main` function is selected, Ghidra creates only an xml file (containing a bytechunk element), so I currently cannot reproduce this.

- What version of Ghidra are you using? Did you compile it yourself? 
- Could you share the `hello_world.xml` and `hello_world.bytes` files you're getting?

**Comment by ignatirabo** [comment]
Oh I see. My mistake was exporting the program as an XML file. I did not know about "debug function decompilation". Now I am getting an XML file with `bytechunk` but I do not see anything being outputted by DecompVis.

![image](https://github.com/user-attachments/assets/32c45d4c-4fda-47cf-8254-7f9059718c0b)

What could be the cause?

**Comment by LukeSerne** [comment]
Not sure. From the screenshot, it seems that no xml file has been loaded.

It might be the case that you haven't set the Ghidra folder or the path to the `decomp_dbg` executable. Check the [usage instructions in the readme](https://github.com/LukeSerne/DecompVis?tab=readme-ov-file#usage) for resolving this.

If that's not the issue, please describe step by step what you're doing that leads to this screen.
