### ISSUE TITLE
Neatly sort P-CODE ops by their address

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [LukeSerne/DecompVis#6]
Unsorted, it's a mess:
![image](https://github.com/user-attachments/assets/8bfd7f98-3a87-46d7-9721-e206e0cf8897)

**Comment by LukeSerne** [comment]
The 'Raw P-CODE' entry is included more for the 'P-CODE' tab in the 'Information' panel than the graph view. The graph view is supposed to purely reflect the relation between nodes, not their addresses.

For an xml from a simple 'hello world' function, I do however get some links in the 'Raw P-CODE' stage (see screenshot below). It seems like those links have not been found for your xml...

![image](https://github.com/user-attachments/assets/ec30afbd-d380-4347-a3dd-27e7a271c340)

Regardless, the old version of the layout algorithm didn't take node sizes into account, which caused overlapping nodes (as shown in your screenshot). In commit fe4db3d, this problem should be alleviated.

You should try with the latest version on master. Hopefully, the graph view no longer is a mess.

**Comment by H-A-M-G-E-R** [comment]
uhh, still doesn't work
![image](https://github.com/user-attachments/assets/3eebb3ee-aee4-4e17-b9e4-d03cc5d1460c)

**Comment by LukeSerne** [comment]
Could you share the input xml you're using?

**Comment by H-A-M-G-E-R** [comment]
[GeegaSpawningFromX.xml.txt](https://github.com/user-attachments/files/18267474/GeegaSpawningFromX.xml.txt)

**Comment by H-A-M-G-E-R** [comment]
from metroid fusion decomp
https://github.com/H-A-M-G-E-R/mf

**Comment by LukeSerne** [comment]
Thanks for sharing the xml. However, I still cannot reproduce your issue. When I open the xml, I get:

![](https://github.com/user-attachments/assets/2aef200e-ed65-43ea-b7e7-64b27329b5fc)

What version of ghidra did you build `decomp_dbg` from? Could you share the `decomp_dbg` binary you built as well?

**Comment by H-A-M-G-E-R** [comment]
https://github.com/H-A-M-G-E-R/ghidra
my fork

**Comment by LukeSerne** [comment]
Unfortunately, I still cannot reproduce this, even when building `decomp_dbg` from your fork of Ghidra.

![](https://github.com/user-attachments/assets/b088ab2e-e5d8-44c4-8bb2-18b4e4e14f29)

Some more questions that might help reproducing this error.

1. Do you get any popups when loading the xml?
2. What version of DecompVis are you using? You can check this by running `git rev-parse HEAD` in the folder in which you cloned DecompVis.
3. What folder is selected for the "Ghidra folder"?
4. What file is selected as "decomp_dbg"?

**Comment by H-A-M-G-E-R** [comment]
version `fe4db3d0cc1025aafa7aab051f3f1efc4314229b`
and the settings.ini  is
```
[General]
decomp_dbg_path=@Variant(\0\0\0\x7f\0\0\0\x18PySide::PyObjectWrapper\0\0\0\0\xb8\x80\x4\x95\xad\0\0\0\0\0\0\0\x8c\apathlib\x94\x8c\tPosixPath\x94\x93\x94(\x8c\x1/\x94\x8c\x4home\x94\x8c\x5h-a-m\x94\x8c\tDocuments\x94\x8c\x6ghidra\x94\x8c\x5\x62uild\x94\x8c\x4\x64ist\x94\x8c\xfghidra_11.3_DEV\x94\x8c\x6Ghidra\x94\x8c\bFeatures\x94\x8c\nDecompiler\x94\x8c\x3src\x94\x8c\tdecompile\x94\x8c\x3\x63pp\x94\x8c\ndecomp_dbg\x94t\x94R\x94.)
ghidra_dir=@Variant(\0\0\0\x7f\0\0\0\x18PySide::PyObjectWrapper\0\0\0\0r\x80\x4\x95g\0\0\0\0\0\0\0\x8c\apathlib\x94\x8c\tPosixPath\x94\x93\x94(\x8c\x1/\x94\x8c\x4home\x94\x8c\x5h-a-m\x94\x8c\tDocuments\x94\x8c\x6ghidra\x94\x8c\x5\x62uild\x94\x8c\x4\x64ist\x94\x8c\xfghidra_11.3_DEV\x94t\x94R\x94.)
```

**Comment by LukeSerne** [comment]
Hmm, interesting. Everything seems to be correct. Weird that I can't reproduce it...

1. Do the nodes also overlap for other p-code stages?
2. It's weird that the information tab seems to be empty in your screenshots. Is it really empty? If so, is it empty for all stages? Is it just the P-CODE tab, or is the diff tab empty as well?
3. Do any errors appear in the terminal window while running the application? If so, could you share the traceback?

**Comment by H-A-M-G-E-R** [comment]
```
[x] Starting local process '/home/h-a-m/Documents/ghidra/build/dist/ghidra_11.3_[.] Starting local process '/home/h-a-m/Documents/ghidra/build/dist/ghidra_11.3_[+] Ghidra/Features/Decompiler/src/decompile/cpp/decomp_dbg': pid 449552
[*] Stopped process '/home/h-a-m/Documents/ghidra/build/dist/ghidra_11.3_DEV/Ghidra/Features/Decompiler/src/decompile/cpp/decomp_dbg' (pid 449552)
Traceback (most recent call last):
  File "/home/h-a-m/Documents/DecompVis/venv/lib/python3.12/site-packages/pydot/core.py", line 1851, in create
    stdout_data, stderr_data, process = call_graphviz(
                                        ^^^^^^^^^^^^^^
  File "/home/h-a-m/Documents/DecompVis/venv/lib/python3.12/site-packages/pydot/core.py", line 211, in call_graphviz
    process = subprocess.Popen(
              ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'dot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/h-a-m/Documents/DecompVis/main.py", line 348, in handle_list_change
    self.graph_view.set_graph(state.get_graph())
  File "/home/h-a-m/Documents/DecompVis/ui.py", line 336, in set_graph
    self.set_pos()
  File "/home/h-a-m/Documents/DecompVis/ui.py", line 341, in set_pos
    positions = layout_algorithm(self._graph)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h-a-m/Documents/DecompVis/util.py", line 245, in layout_algorithm
    pos = networkx.nx_pydot.pydot_layout(quoted_graph, prog=layout_prog)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h-a-m/Documents/DecompVis/venv/lib/python3.12/site-packages/networkx/drawing/nx_pydot.py", line 320, in pydot_layout
    D_bytes = P.create_dot(prog=prog)
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h-a-m/Documents/DecompVis/venv/lib/python3.12/site-packages/pydot/core.py", line 158, in __create_method
    return self.create(format=f, prog=prog, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/h-a-m/Documents/DecompVis/venv/lib/python3.12/site-packages/pydot/core.py", line 1860, in create
    raise OSError(*args)
FileNotFoundError: [Errno 2] "dot" not found in path.
```
empty in all stages, diff and p-code tabs, and nodes overlap in all stages

**Comment by LukeSerne** [comment]
Ah, it seems like you don't have GraphViz installed. You can follow the installation instructions at https://graphviz.org/download/. I'll add this to the readme as well.

Please let me know if installing graphviz fixes the issue.

**Comment by H-A-M-G-E-R** [comment]
It worked!
![image](https://github.com/user-attachments/assets/d383af1f-6890-4f88-a515-966adeba7a0c)
